import Head from "next/head";
import Input from "../components/form/Input";
import Aksesuar from "../components/layout/Aksesuar";
import Header from "../components/layout/Header";
import Home from "./home";



export default function Index() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
         rel="preconnect" 
  href="https://fonts.gstatic.com"
   crossOrigin="true" />

      </Head>
      <Home/>
      <div className="p-20 container mx-auto">
        <Input />
      </div>
     
      
    </div>
  );
}
